{{- if or
  (not (values .Values.nextcloud.hooks | compact | empty))
  .Values.nextcloud.appManagement.enabled
}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nextcloud.fullname" . }}-hooks
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $hook, $shell := .Values.nextcloud.hooks }}
  {{- if $shell }}
  {{ $hook }}.sh: {{ $shell | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.nextcloud.appManagement.enabled }}
  app-management.sh: {{ tpl (.Files.Get "files/app-management.sh.gotmpl") . | quote }}
  {{- end }}
{{- end }}
