{{- if .Values.cronjobs.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nextcloud.fullname" . }}-cronjobs
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
