{{- if .Values.cronjobs.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "nextcloud.fullname" . }}-cronjobs
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "nextcloud.fullname" . }}-cronjobs
subjects:
  - kind: ServiceAccount
    name: {{ template "nextcloud.fullname" . }}-cronjobs
{{- end }}
