{{- if or .Values.mariadb.enabled .Values.externalDatabase.enabled .Values.postgresql.enabled }}
{{- if not .Values.externalDatabase.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- if .Values.mariadb.enabled }}
  db-username: {{ .Values.mariadb.auth.username | quote }}
  db-password: {{ .Values.mariadb.auth.password | quote }}
  {{- else if .Values.postgresql.enabled }}
  db-username: {{ .Values.postgresql.global.postgresql.auth.username | quote }}
  db-password: {{ .Values.postgresql.global.postgresql.auth.password | quote }}
  {{- else }}
  db-username: {{ .Values.externalDatabase.user | quote }}
  db-password: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
{{- end }}
{{- end }}
