{{- if .Values.nginx.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nextcloud.fullname" . }}-nginxconfig
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |-
    {{- if .Values.nginx.config.default }}
    {{- tpl (.Files.Get "files/nginx.config.gotmpl") . | nindent 4 }}
    {{- else }}
    {{- .Values.nginx.config.custom | nindent 4 }}
    {{- end }}
{{- end }}
