metrics:
  enabled: true
  image:
    pullSecrets:
      - "registry-pull"
  podAnnotations:
    fakeVersion: unreleased
  podLabels:
    team: cool
  resources:
    requests:
      memory: 100Mi
  service:
    type: LoadBalancer
    loadBalancerIP: 100.64.0.1
    annotations:
      fakeVersion: unreleased
    labels:
      team: cool

nextcloud:
  configs:
    my.config.php: |-
      <?php

  phpConfigs:
    redis.ini: |-
      session.save_handler = redis
      session.save_path = "tcp://host1:6379?weight=1, tcp://host2:6379?weight=2&timeout=2.5"

image:
  flavor: fpm

nginx:
  enabled: true
  config:
    default: false
    # without default chart-testing needs to call /status.php for healthy probe
    custom: |-
      upstream php-handler {
        server 127.0.0.1:9000;
      }
      server {
        listen 80;
        root /var/www/html;
        location ~ \.php(?:$|/) {
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass php-handler;
        }
      }
